# Generated by Django 5.1.5 on 2025-01-30 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=5)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'surname', 'date_of_birth'), name='unique_person')],
            },
        ),
    ]
